language: python

python:
  - "2.7"
  - "3.7"
  - "3.8"

env:
  - PYTHONPATH=$PYTHONPATH:$(pwd)/mxcubecore:$(pwd)/mxcube MXCUBE_CORE_CONFIG=$(pwd)/mxcubecore/mxcubecore/configuration/mockup/qt:$(pwd)/mxcubecore/mxcubecore/configuration/mockup 

services: xvfb

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install mesa-common-dev python-pyqt5; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry python -m pip install -r requirements_python2.txt PyVirtualDisplay==0.2.5 pytest-xvfb PyYAML pylint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then travis_retry pip3 install -r requirements_python3.txt PyQt5 pytest-xvfb PyYAML pylint; fi
  - git clone https://github.com/mxcube/mxcubecore

before_script:
  - "export DISPLAY=:99.0"

script:
  #- cd test
  #- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_wait 20 python -m pytest; fi
  #- if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then travis_wait 20 python3 -m pytest; fi
  #- cd ..
  - pylint mxcubeqt -E --extension-pkg-whitelist=PyQt5,PyQt4
